// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause():Promise<void>;

export function PlayYoutube(arg1:string):Promise<void>;

export function Resume():Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Stop():Promise<void>;
