// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PlayYoutube(arg1) {
  return window['go']['main']['App']['PlayYoutube'](arg1);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
